### ISSUE TITLE
RequireJS incompatibility back? (Django 1.8.6)

### ISSUE THREAD

**Issue by tammyalexandra** [django-debug-toolbar/django-debug-toolbar#772] opened 2015-11-16 00:02 UTC
I've read through all the past bugs related to this and the release notes, but alas, despite what they promise I cannot get any version of the toolbar running with Django 1.8.6 out of the box.  The more recent versions cause JS errors:

    Uncaught TypeError: define is not a function(anonymous function)

And the older ones cause 500s:

    django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.templates: "cannot import name get_standard_processors"

The only way to get it to work is to do what's suggested here:  https://github.com/django-debug-toolbar/django-debug-toolbar/issues/605#issuecomment-45391760

I didn't see anything about this in the documentation, as was suggested at point, so perhaps this bug is back?

(Admittedly, while I am up-to-date on my Django dependencies, I am behind on JS:  RequireJS 2.1.1, JQuery 1.10.2.)

Thank you!

**Comment by aaugustin** [comment] 2016-02-21 17:08
I suspect this is a duplicate of #605. Please comment if you think something else is going on.

**Closed by aaugustin** 2016-02-21 17:08 UTC
Labels: RequireJS
