### ISSUE TITLE
slow loading of media files

### ISSUE THREAD

**Issue by clime** [django-debug-toolbar/django-debug-toolbar#517] opened 2013-12-28 23:39 UTC
Hey,

upgrading to 1.0 seems to cause slow downloading of media files into browser. They are loaded in batches of aprox. six images and there is always a long pause between loading of each batch. Here is screenshot from chrome developer tools:

![screenshot from 2013-12-29 00 38 20](https://f.cloud.github.com/assets/2030528/1818664/1ae16846-7019-11e3-885d-4362ff28af3d.png)

With debug toolbar disabled, this doesn't happen and images are all loaded almost immediatelly.

I am always cleaning the browser cache between individual tries to get the results.

**Comment by spookylukey** [comment] 2015-04-14 12:00
I think I have tracked this down:

The slowness can be eliminated by removing the call to `get_staticfiles_finders` from `StaticFilesPanel.process_response`. The problem is just that this method takes a non-trivial amount of time to run when you have a lot of media files, for instance (3000+ on my current project).

A further problem is that this expensive method is run for every request, including ones that will never need it, because they don't return HTML - including requests for the media files themselves. So, for media heavy sites (where the total number of media files is large, and the number per page is likely to be large), you get hit on both counts.

Digging deeper, `Panel.process_response` is run for every panel, whether or not the response can have the toolbar inserted. This seems like a very unnecessary performance hit! The current design allows `Panel.process_response` to return its own response, but this is only used once, by the redirect panel.

So it seems that for most of the panels, the `process_response` method should be empty and there should be a `generate_stats` method instead, which is called only conditionally after `DebugPanelMiddleware.process_response` has decided that it is going to insert the toolbar.

**Comment by jezdez** [comment] 2015-04-14 12:54
@spookylukey Nice digging! That makes sense (yikes, 3k files!), your proposed API changes make sense to me, too.

**Comment by danpaulson** [comment] 2015-07-01 20:16
Bump! Running in to this on a rather large site, wondering if it's slated to be fixed any time soon?

**Comment by tim-schilling** [comment] 2015-07-02 00:59
It probably won't be any time soon, but I'll try to get a solution together the next time I spend a large chunk of time on the project.

**Comment by tim-schilling** [comment] 2015-07-02 01:10
@spookylukey When you said most of the panels' ```process_response``` methods should be empty, were you referring to the ```RedirectsPanel``` as the one exception? If so, I think we may want to change your design so that the current ```process_response``` only gets called when it's going to be inserted and then create a ```interrupt_response``` method that panels like ```RedirectsPanel``` need to be called before.

The reasoning is that if we change the purpose of ```process_response``` and use a different method to handle that logic, it will impact most of the third party panels. Since development on the toolbar is slow, I'd rather keep the API as stable as possible. Obviously any third party panels that return a response would still need to be updated and I think that's only https://github.com/joymax/django-dtpanel-htmltidy.

**Comment by spookylukey** [comment] 2015-07-02 15:42
@tim-schilling it's exactly because of the compatibility problem with 3rd parties that I made the suggestion that way round. Existing `Panel` subclasses may assume that their `process_response` method gets called for every request (for example, something that is a drop-in replacement for the current `RedirectsPanel`). If you want to keep full compatibility with them (which you might not care about), you can't change it so that `process_response` is only called sometimes.

With my suggestion, those 3rd party panels wouldn't be affected - they would be using `process_response` for the wrong purpose, but they would still work. The upgrade notes would say "For best performance, if you are not returning an actual response in `process_response`, you should rename it to `generate_stats`" (or choose some better name).

How you want to handle this is entirely up to you, though.

**Comment by tim-schilling** [comment] 2015-07-02 16:03
Ah, gotcha. That makes sense, thank you for clarifying!

**Comment by tim-schilling** [comment] 2015-07-14 01:41
Can someone test out #731 to verify that it's improved the loading of media files before I merge it in?

**Comment by aaugustin** [comment] 2015-10-06 10:01
Closing as #731 was merged.

**Closed by aaugustin** 2015-10-06 10:01 UTC
Labels: Bug
