### ISSUE TITLE
Toolbar is invisable/hidden when using Twitter Bootstrap v4.0 (because of normalize.css/scss)

### ISSUE THREAD

**Issue by timmyomahony** [django-debug-toolbar/django-debug-toolbar#798] opened 2016-01-07 20:36 UTC
When you use Django debug toolbar with the new Bootstrap 4.0 the toolbar doesn't display correctly (it's totally hidden). This seems to be due to Bootstraps dependence on normalize.scss which has a CSS selector for the `[hidden]` attribute which is used in the Django debug toolbar templates. 

[This is the offending line from the normalize scss file in Bootstrap:](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_normalize.scss#L77)

```
//
// Address `[hidden]` styling not present in IE 8/9/10.
// Hide the `template` element in IE 8/9/10/11, Safari, and Firefox < 22.
//

[hidden],
template {
  display: none;
}
```

and it is affecting [this Django debug toolbar template:](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/debug_toolbar/templates/debug_toolbar/base.html#L13)

```
<div id="djDebug" hidden="hidden" dir="ltr"
```

I'm not sure why the `hidden` attribute is being used, maybe it's as simple as removing it? For the moment I am simply removing those selectors from bootstrap manually

**EDIT**

There is a [second file in bootstrap that is causing issues called `reboot.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L351):

```
// Always hide an element with the `hidden` HTML attribute (from PureCSS).
[hidden] {
  display: none !important;
}
```

**Comment by mvasilkov** [comment] 2016-02-13 17:18
I can confirm, happened to me just now. Bootstrap v4 alpha 2.

**Comment by aaugustin** [comment] 2016-02-21 15:14
Duplicate of https://github.com/django-debug-toolbar/django-debug-toolbar/issues/742.

**Closed by aaugustin** 2016-02-21 15:14 UTC

**Comment by eriktelepovsky** [comment] 2016-03-02 10:42
Thanks @mvasilkov
