### ISSUE TITLE
debug tool bar break when template cached loader activate

### ISSUE THREAD

**Issue by leonardoo** [django-debug-toolbar/django-debug-toolbar#701] opened 2015-03-24 14:00 UTC
when i config this in my settings toolbars break

```python
TEMPLATE_LOADERS = ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',])
```

**Comment by ngzhian** [comment] 2015-04-02 00:03
Your setting looks broken, `TEMPLATE_LOADERS` should be a string, so your code should be
```
TEMPLATE_LOADERS = ('django.template.loaders.cached.Loader',
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader')
```
also see [this](https://docs.djangoproject.com/en/1.8/ref/settings/#template-loaders)

**Comment by leonardoo** [comment] 2015-04-02 03:43
@ngzhian it's not broken, when you use cached templates, must be config like it

https://docs.djangoproject.com/en/1.7/ref/templates/api/#django.template.loaders.cached.Loader

TEMPLATE_LOADERS = (
    ('django.template.loaders.cached.Loader', (
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
    )),
)

**Comment by ngzhian** [comment] 2015-04-02 03:57
@leonardoo ic, what's the error, might be related to #670 ?

**Comment by tim-schilling** [comment] 2015-04-26 01:32
I've attempted to reproduce and could not. I'm closing this for the time being because no details about the error have been given.

**Closed by tim-schilling** 2015-04-26 01:32 UTC
