### ISSUE TITLE
Django 1.8 *** AttributeError: 'RequestContext' object has no attribute '_processors'

### ISSUE THREAD

**Issue by rvanlaar** [django-debug-toolbar/django-debug-toolbar#692] opened 2015-02-26 15:11 UTC
The debug_toolbar/panels/templates.py `_request_context__init__` is not up to date with the
RequestContext from Django 1.8.

A couple of attributes are not set. This raises the following error in bind_template:
*** AttributeError: 'RequestContext' object has no attribute '_processors'

Add these three lines after the if/else from processors to fix these issues:
```
    self._processors = processors
    self._processors_index = len(self.dicts)
    self.request = request
```

**Comment by aaugustin** [comment] 2015-02-26 21:01
Indeed, the DDT hasn't been ported to 1.8 beta yet. This is a duplicate of #668.

**Closed by aaugustin** 2015-02-26 21:01 UTC

**Comment by jamespacileo** [comment] 2015-03-04 22:35
Any change there could be a django-1.8 branch? Seems like dust has settled on the context processor api.

**Comment by tim-schilling** [comment] 2015-03-05 02:03
This is being worked on in #694
