### ISSUE TITLE
ajax loader frozen. djDebugPanelContent empty and obstructing website / ajax-loader.gif stuck

### ISSUE THREAD

**Issue by mykhul** [django-debug-toolbar/django-debug-toolbar#703] opened 2015-04-08 02:53 UTC
I am using Django 1.8, with a basic django toolbar set up. The toolbar shows up and looks as though it is working, however I am seeing 3 little "loading" indicator dots (ajax-loader.gif), with a large invisible (div class="djDebugPanelContent")...(/div) getting in the way of the website and preventing the toolbar from working as expected. Someone on IRC also noted that they are experiencing the same issue on Django 1.7 and have tried both Toolbar versions 1.2.2 and 1.3.

**Comment by nikolas** [comment] 2015-04-08 02:58
I'm also seeing this issue, tested with django 1.7.7 and 1.8, djdt 1.2.2 and 1.3. I don't know how helpful this is, but here's a screenshot of the problem on my site:

![2015-04-07-225953_85x72_scrot](https://cloud.githubusercontent.com/assets/59292/7038025/7bca2002-dd79-11e4-8d48-b0c3b35ea4e7.png)

**Comment by tim-schilling** [comment] 2015-04-08 14:10
Does it go away after a couple of refreshes? Not saying that it's not a bug, just assessing the severity.

**Comment by mykhul** [comment] 2015-04-08 14:12
I am still trying to troubleshoot it. it does not go away.

**Comment by nikolas** [comment] 2015-04-08 14:15
Yeah, it doesn't go away for me. My workaround is just disabling the debug toolbar.

**Comment by mykhul** [comment] 2015-04-08 19:28
updating the django-toolbar's javascript files in /static/ may have solved the issue! nikolas, can you confirm?

**Comment by nikolas** [comment] 2015-04-08 19:33
@mykhul yes, that fixes it for me. We can close this issue.

**Comment by mykhul** [comment] 2015-04-08 19:34
That's great! Hope it helps someone else that may be having the same problem.

**Closed** 2015-04-08 19:35 UTC
