### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagForm needs updating.

### ISSUE THREAD

**Issue by priya124** [django-debug-toolbar/django-debug-toolbar#827] opened 2016-05-20 12:47 UTC
Below mensioned error is occuring while installaing RatticDB on ubuntu 12.04
./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/apps/RatticWeb/cred/models.py", line 18, in <module>
    class TagForm(ModelForm):
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 235, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagForm needs updating.

**Comment by tim-schilling** [comment] 2016-05-20 12:53
Duplicate of #826

**Closed by tim-schilling** 2016-05-20 12:53 UTC
